config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins
  devise_for :users

  namespace :admin do
    resources :carriers, only: %i[index show new create edit update]
    resources :price_ranges, only: %i[index new create edit update]
    resources :delivery_distances, only: %i[index new create edit update]
  end

  namespace :user do
    resources :vehicles, only: %i[index new create edit update]
    resources :distance_prices, only: %i[index new create edit update]
    resources :delivery_times, only: %i[index new create edit update]
    resources :carriers, only: %i[show edit update]
  end

  resources :orders, only: %i[index show new create edit update] do
    resources :tracking_logs, only: %i[new create]
    get 'search', on: :collection
    get 'budgets', on: :collection
    post 'accepted', on: :member
    post 'delivered', on: :member
    post 'rejected', on: :member
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :carrier, optional: true

  validates :model, :brand, :year, :license_plate, presence: true
end

app/controllers/user/vehicles_controller.rb
class User::VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :this_carrier

  def index
    @vehicles = Vehicle.where(carrier_id: current_user.carrier_id)
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save

    if @vehicle.save
      redirect_to user_vehicles_path, notice: 'Veículo salvo com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento dos campos.'
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    vehicle_params

    if @vehicle.update(vehicle_params)
      flash[:notice] = 'Veículo atualizado com sucesso.'
      redirect_to user_vehicles_path
    else
      flash[:alert] = 'Atualização falhou. Verifique o preenchimento dos campos.'
      render :edit
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:model, :brand, :year, :license_plate, :carrier_id)
  end

  def this_carrier
    @carrier = Carrier.find(current_user.carrier_id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :this_carrier

  def index
    @vehicles = Vehicle.where(carrier_id: current_user.carrier_id)
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save

    if @vehicle.save
      redirect_to vehicles_path, notice: 'Veículo salvo com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento dos campos.'
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    vehicle_params

    if @vehicle.update(vehicle_params)
      flash[:notice] = 'Veículo atualizado com sucesso.'
      redirect_to vehicles_path
    else
      flash[:alert] = 'Atualização falhou. Verifique o preenchimento dos campos.'
      render :edit
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:model, :brand, :year, :license_plate, :carrier_id)
  end

  def this_carrier
    @carrier = Carrier.find(current_user.carrier_id)
  end
end

app/views/vehicles/_form.html.erb
<div class="m-auto" style="max-width: 700px">
<%= form_with model: @vehicle do |v| %>
  <div>
    <%= v.label :model, 'Modelo' %>
    <%= v.text_field :model %>
  </div>
  
  <div>
    <%= v.label :brand, 'Marca' %>
    <%= v.text_field :brand %>
  </div>

  <div>
    <%= v.label :year, 'Ano'%>
    <%= v.number_field :year %>
  </div>

  <div>
    <%= v.label :license_plate, 'Placa' %>
    <%= v.text_field :license_plate %>
  </div>

  <%= v.hidden_field :carrier_id, value: @carrier.id %>

  <div>
    <%= v.submit 'Enviar' %>
  </div>

<% end  %>

<%= link_to 'Voltar', vehicles_path %>

app/views/vehicles/index.html.erb
<h1 class="text-center"><%= @carrier.brand_name %></h1>
<h2 class= "text-center">Cadastro de Veículos</h2>
<br /><br />
<div class="text-center">
  <%= link_to '+ Adicionar Veículo', new_vehicle_path, class: 'btn btn-primary' %>
</div>
<br /><br/>

<table class="table align-middle">
  <tr>
    <th>Modelo</th>
    <th>Ano</th>
    <th>Marca</th>
    <th>Placa</th>
    <th>Transportadora</th>
    <th>Ações</th>
  </tr>
  <% @vehicles.each do |v| %>
    <tr>
      <td><%= v.model %></td>
      <td><%= v.year %></td>
      <td><%= v.brand %></td>
      <td><%= v.license_plate %></td>
      <td><%= v.carrier.brand_name %></td>
      <td><%= link_to 'Editar', edit_vehicle_path(v), class: 'btn btn-outline-warning' %></td>
    </tr>
  <% end  %>
</table>