config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins
  devise_for :users

  namespace :admin do
    resources :carriers, only: %i[index show new create edit update]
    resources :price_ranges, only: %i[index new create edit update]
    resources :delivery_distances, only: %i[index new create edit update]
  end

  namespace :user do
    resources :vehicles, only: %i[index new create edit update]
    resources :distance_prices, only: %i[index new create edit update]
    resources :delivery_times, only: %i[index new create edit update]
    resources :carriers, only: %i[show edit update]
  end

  resources :orders, only: %i[index show new create edit update] do
    resources :tracking_logs, only: %i[new create]
    get 'search', on: :collection
    get 'budgets', on: :collection
    post 'accepted', on: :member
    post 'delivered', on: :member
    post 'rejected', on: :member
  end
end

app/models/distance_price.rb
class DistancePrice < ApplicationRecord
  belongs_to :carrier
  belongs_to :price_range

  validates :price_range_id,
            uniqueness: { scope: :carrier_id,
                          message: 'Preço por km já cadastrado para esta Transportadora. Tente editar o cadastro.' }
end

app/controllers/distance_prices_controller.rb
class DistancePricesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_carrier

  def index
    @price_ranges = PriceRange.all
    @distance_prices = DistancePrice.where(carrier_id: current_user.carrier_id)
  end

  def new
    @price_range = PriceRange.find(params[:price_range_id])
    @distance_price = DistancePrice.new
  end

  def create
    @distance_price = DistancePrice.new(params.require(:distance_price).permit(:km_price, :carrier_id, :price_range_id))
    @distance_price.save

    if @distance_price.save
      redirect_to distance_prices_path, notice: 'Preço por Km cadastrado com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento do cadastro.'
      render :new
    end
  end

  def edit
    @distance_price = DistancePrice.find(params[:id])
    @price_range = PriceRange.find(@distance_price.price_range_id)
  end

  def update
    @distance_price = DistancePrice.find(params[:id])
    @price_range = PriceRange.find(@distance_price.price_range_id)

    if @distance_price.update(params.require(:distance_price).permit(:km_price, :carrier_id, :price_range_id))
      redirect_to distance_prices_path, notice: 'Preço por Km atualizado com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento do cadastro.'
      render :new
    end
  end

  private

  def set_carrier
    @carrier = Carrier.find(current_user.carrier_id)
  end
end

app/controllers/user/distance_prices_controller.rb
class User::DistancePricesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_carrier

  def index
    @price_ranges = PriceRange.all
    @distance_prices = DistancePrice.where(carrier_id: current_user.carrier_id)
  end

  def new
    @price_range = PriceRange.find(params[:price_range_id])
    @distance_price = DistancePrice.new
  end

  def create
    @distance_price = DistancePrice.new(params.require(:distance_price).permit(:km_price, :carrier_id, :price_range_id))
    @distance_price.save

    if @distance_price.save
      redirect_to user_distance_prices_path, notice: 'Preço por Km cadastrado com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento do cadastro.'
      render :new
    end
  end

  def edit
    @distance_price = DistancePrice.find(params[:id])
    @price_range = PriceRange.find(@distance_price.price_range_id)
  end

  def update
    @distance_price = DistancePrice.find(params[:id])
    @price_range = PriceRange.find(@distance_price.price_range_id)

    if @distance_price.update(params.require(:distance_price).permit(:km_price, :carrier_id, :price_range_id))
      redirect_to user_distance_prices_path, notice: 'Preço por Km atualizado com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento do cadastro.'
      render :new
    end
  end

  private

  def set_carrier
    @carrier = Carrier.find(current_user.carrier_id)
  end
end

app/views/distance_prices/index.html.erb
<br />
<h1 class="text-center"><%= current_user.carrier.brand_name %></h1>
<h2 class= "text-center">Configuração de Preços por km</h2>
<br /><br />
<table class="table text-center m-auto" style="max-width: 800px">
  <thead>
    <tr>
      <th rowspan="2">#</th>
      <th colspan="2">Volume</th>
      <th colspan="2">Peso</th>
      <th rowspan="2">Preço/km</th>
      <th rowspan="2">Ação</th>
    </tr>
    <tr>
      <th>De</th>
      <th>Até</th>
      <th>De</th>
      <th>Até</th>
    </tr>
  </thead>
<% @price_ranges.each do |price_range|  %>
  <tr>
    <td><%= price_range.id %></td>
    <td><%= number_with_precision(price_range.volume_start) %> m³</td>
    <td><%= number_with_precision(price_range.volume_end) %> m³</td>
    <td><%= number_with_precision(price_range.weight_start) %> kg</td>
    <td><%= number_with_precision(price_range.weight_end) %> kg</td>
    <% range_price = @carrier.distance_prices.find_by(price_range_id: price_range.id) %>
    <td>R$ <%= range_price.nil? ? ' ' : number_with_precision(range_price.km_price, precision: 2) %></td>
    <td>
      <%= range_price.nil? ? (link_to 'Criar', new_distance_price_path(carrier_id: @carrier.id, price_range_id: price_range.id)) : (link_to 'Editar', edit_distance_price_path(range_price.id)) %>
    </td>
  </tr>
<% end  %>
</table>