config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins
  devise_for :users

  namespace :admin do
    resources :carriers, only: %i[index show new create edit update]
    resources :price_ranges, only: %i[index new create edit update]
    resources :delivery_distances, only: %i[index new create edit update]
  end

  namespace :user do
    resources :vehicles, only: %i[index new create edit update]
    resources :distance_prices, only: %i[index new create edit update]
    resources :delivery_times, only: %i[index new create edit update]
    resources :carriers, only: %i[show edit update]
  end

  resources :orders, only: %i[index show new create edit update] do
    resources :tracking_logs, only: %i[new create]
    get 'search', on: :collection
    get 'budgets', on: :collection
    post 'accepted', on: :member
    post 'delivered', on: :member
    post 'rejected', on: :member
  end
end

app/models/carrier.rb
class Carrier < ApplicationRecord
  has_many :users
  has_many :distance_prices
  has_many :price_ranges, through: :distance_prices
  has_many :delivery_times
  has_many :delivery_distances, through: :delivery_times
  has_many :orders
  has_many :vehicles

  enum status: { active: 0, inactive: 5 }

  validates :brand_name, :corporate_name, :email_domain, :taxpayer_number, presence: true
  validates :taxpayer_number, length: { is: 14, message: 'deve ter 14 digitos.' }
  validates :taxpayer_number, numericality: true
  validates :taxpayer_number, :email_domain, uniqueness: true

  def total_order_value(volume, weight, distance)
    price_ranges.each do |pr|
      if (volume >= pr.volume_start && volume <= pr.volume_end) && (weight >= pr.weight_start && weight <= pr.weight_end)
        return distance * DistancePrice.find_by(carrier_id: id, price_range_id: pr.id).km_price
      end
    end
  end

  def estimated_delivery_date(distance)
    delivery_distances.each do |dd|
      if distance >= dd.from_km && distance <= dd.to_km
        return DeliveryTime.find_by(carrier_id: id, delivery_distance_id: dd.id).time
      end
    end
  end
end

app/controllers/admin/carriers_controller.rb
class Admin::CarriersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_carrier, only: %i[show edit update]

  def index
    @carriers = Carrier.all
  end

  def show; end

  def new
    @carrier = Carrier.new
  end

  def create
    @carrier = Carrier.new(carrier_params)
    @carrier.save

    if @carrier.save
      redirect_to [:admin, @carrier], notice: 'Transportadora salva com sucesso.'
    else
      flash.now[:alert] = 'Verifique o preenchimento do cadastro.'
      render :new
    end
  end

  def edit; end

  def update
    carrier_params

    if @carrier.update(carrier_params)
      flash[:notice] = 'Transportadora atualizada com sucesso.'
      redirect_to admin_carrier_path
    else
      flash[:alert] = 'Atualização não realizada. Verifique o preenchimento do cadastro.'
      render :edit
    end
  end

  private

  def set_carrier
    @carrier = Carrier.find(params[:id])
  end

  def carrier_params
    params.require(:carrier).permit(
      :brand_name, :corporate_name, :email_domain, :taxpayer_number, :status
    )
  end
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_carrier, only: %i[show edit update]

  def index
    @carriers = Carrier.all
  end

  def show; end

  def new
    @carrier = Carrier.new
  end

  def create
    @carrier = Carrier.new(carrier_params)
    @carrier.save

    if @carrier.save
      redirect_to @carrier, notice: 'Transportadora salva com sucesso.'
    else
      flash[:alert] = 'Verifique o preenchimento do cadastro.'
      render :new
    end
  end

  def edit; end

  def update
    carrier_params

    if @carrier.update(carrier_params)
      flash[:notice] = 'Transportadora atualizada com sucesso.'
      redirect_to carrier_path
    else
      flash[:alert] = 'Atualização não realizada. Verifique o preenchimento do cadastro.'
      render :edit
    end
  end

  private

  def set_carrier
    @carrier = Carrier.find(params[:id])
  end

  def carrier_params
    params.require(:carrier).permit(
      :brand_name, :corporate_name, :email_domain, :taxpayer_number, :status
    )
  end
end

app/controllers/user/carriers_controller.rb
class User::CarriersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_carrier, only: %i[show edit update]

  def show; end

  def edit; end

  def update
    carrier_params
    if @carrier.update(carrier_params)
      redirect_to user_distance_prices_path, notice: 'Preço mínimo definido com sucesso.'
    else
      flash.now[:alert] = 'Preço mínimo não atualizado. Verifique o preenchimento do cadastro.'
      render :edit
    end
  end

  private

  def carrier_params
    params.require(:carrier).permit(:brand_name, :corporate_name, :email_domain, :taxpayer_number, :minimum_price)
  end

  def set_carrier
    @carrier = Carrier.find(current_user.carrier_id)
  end
end

app/views/admin/carriers/_form.html.erb
<%= form_with model: [:admin, @carrier] do |c| %>
  <div>
    <%= c.label :corporate_name %>
    <%= c.text_field :corporate_name %>
  </div>
  
  <div>
    <%= c.label :brand_name %>
    <%= c.text_field :brand_name %>
  </div>

  <div>
    <%= c.label :email_domain %>
    <%= c.text_field :email_domain %>
  </div>

  <div>
    <%= c.label :taxpayer_number %>
    <%= c.number_field :taxpayer_number %>
  </div>

  <div>
    <%= c.label :status %>
    <%= c.select :status, Carrier.statuses.keys %>
  </div>
  <div>
    <%= c.submit 'Enviar' %>
  </div>

<% end %>

<div class="text-center">
  <%= link_to 'Voltar', admin_carriers_path, class: 'btn btn-primary' %>
</div>

app/views/admin/carriers/edit.html.erb
<h1 class="text-center">Editar cadastro de Transportadora</h1>
<%= render partial: 'form' %>

app/views/admin/carriers/index.html.erb
<h1 class="text-center">Transportadoras</h1>
<br />
<div class="text-center">
  <%= link_to '+ Adicionar Transportadora', new_admin_carrier_path, class: 'btn btn-primary' %>
</div>
<br /><br />
<table class="table text-center align-middle">
   <thead>
      <tr>
         <th></th>
         <th>Transportadora</th>
         <th>Razão Social</th>
         <th>Status</th>
         <th>Ações</th>
      </tr>
   </thead>
   <tbody>
      <% @carriers.each do |c| %>
         <tr>
            <td><%= c.id %></td>
            <td><%= link_to c.brand_name, [:admin, c]  %></td>
            <td><%= c.corporate_name %></td>
            <td><%= c.status %></td>
            <td><%= link_to 'Editar', edit_admin_carrier_path(c), class: 'btn btn-outline-warning' %></td>
         </tr>
      <% end %>
   <tbody>
</table>

app/views/admin/carriers/new.html.erb
<h1>Cadastrar Transportadora</h1>
<%= render partial: 'form' %>

app/views/admin/carriers/show.html.erb
<h1>Transportadora</h1>

<h2><%= @carrier.brand_name %></h2>
<dl>
  <dt>Razão Social </dt>
  <dd><%= @carrier.corporate_name %></dd>

  <dt>Domínio</dt>
  <dd><%= @carrier.email_domain %></dd>

  <dt>CNPJ</dt>
  <dd><%= @carrier.taxpayer_number %></dd>
  
  <dt>Status</dt>
  <dd><%= @carrier.status %></dd>
</dl>

<%= link_to 'Editar', edit_admin_carrier_path %>