config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins
  devise_for :users

  namespace :admin do
    resources :carriers, only: %i[index show new create edit update]
    resources :price_ranges, only: %i[index new create edit update]
    resources :delivery_distances, only: %i[index new create edit update]
  end

  namespace :user do
    resources :vehicles, only: %i[index new create edit update]
    resources :distance_prices, only: %i[index new create edit update]
    resources :delivery_times, only: %i[index new create edit update]
    resources :carriers, only: %i[show edit update]
  end

  resources :orders, only: %i[index show new create edit update] do
    resources :tracking_logs, only: %i[new create]
    get 'search', on: :collection
    get 'budgets', on: :collection
    post 'accepted', on: :member
    post 'delivered', on: :member
    post 'rejected', on: :member
  end
end

app/models/price_range.rb
class PriceRange < ApplicationRecord
  has_many :distance_prices

  validates :volume_start, :volume_end, :weight_start, :weight_end, presence: true

  def show_price_range
    "#{volume_start}m³ - #{volume_end}m³ / #{weight_start}kg - #{weight_end}kg"
  end
end

app/controllers/admin/price_ranges_controller.rb
class Admin::PriceRangesController < ApplicationController
  before_action :set_price_range, only: [:edit, :update]

  def index
    @price_ranges = PriceRange.order(:volume_start)
  end

  def new
    @price_range = PriceRange.new
  end

  def create
    price_range_params = params.require(:price_range).permit(:volume_start, :volume_end, :weight_start, :weight_end)
    @price_range = PriceRange.new(price_range_params)
  
    if @price_range.save
      redirect_to admin_price_ranges_path, notice: 'Intervalo de Medidas cadastrado com sucesso.'
    else
      render :new
    end
  end

  def edit; end

  def update
    price_range_params = params.require(:price_range).permit(:volume_start, :volume_end, :weight_start, :weight_end)
    @price_range.update(price_range_params)
    if @price_range.save
      redirect_to admin_price_ranges_path, notice: 'Intervalo de Medidas atualizado com sucesso.'
    else
      flash.now[:alert] = 'Verifique os valores inseridos'
      render :edit
    end

  end

  def set_price_range
    @price_range = PriceRange.find(params[:id])
  end

end

app/views/admin/price_ranges/_form.html.erb
<%= form_with model: [:admin, @price_range] do |pr| %>
  <% if @price_range.errors.any? %>
  <div style="color: rgb(255,0,0)">
    <p>Verifique os erros abaixo: </p>
    <ul>
    <% @price_range.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div>
    <%= pr.label :volume_start %>
    <%= pr.number_field :volume_start, step: :any %> m³
  </div>

  <div>
    <%= pr.label :volume_end %>
    <%= pr.number_field :volume_end, step: :any %> m³
  </div>

  <div>
    <%= pr.label :weight_start %>
    <%= pr.number_field :weight_start, step: :any %> kg
  </div>

  <div>
    <%= pr.label :weight_end %>
    <%= pr.number_field :weight_end, step: :any %> kg
  </div>

  <div>
    <%= pr.submit 'Salvar' %>
  </div>
<% end %>

<br /><br />

<div class="text-center">
  <%= link_to 'Voltar', admin_delivery_distances_path, class: 'btn btn-primary' %>
</div>

app/views/admin/price_ranges/edit.html.erb
<h1 class = 'text-center'>Editar Intervalo de Medidas</h1>
<%= render partial: 'form' %>

app/views/admin/price_ranges/index.html.erb
<h1 class="text-center">Gerenciar Intervalos de Medidas</h1>
<h2 class="text-center">para cadastro de preço por km</h2>
<br />
<div class="text-center">
  <%= link_to 'Novo Intervalo de Medidas', new_admin_price_range_path, class: 'btn btn-primary', style: '--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;' %>
</div>
<br />
<table class="table text-center m-auto" style="max-width: 700px">
  <thead>
    <tr>
     <th></th>
     <th colspan="2">Volume</th>
     <th colspan="2">Peso</th>
     <th></th>
    <tr>
      <th></th>
      <th>De</th>
      <th>Até</th>
      <th>De</th>
      <th>Até</th>
      <th>Ação</th>
    </tr>
    </tr>
  </thead>
  <tbody>
    <% count = 1  %>
    <% @price_ranges.each do |pr| %>
    <tr>
      <td><%= count %></td>
      <td><%= number_with_precision(pr.volume_start, precision: 3) %> m³</td>
      <td><%= number_with_precision(pr.volume_end, precision: 3) %> m³</td>
      <td><%= number_with_precision(pr.weight_start, precision: 3) %> kg</td>
      <td><%= number_with_precision(pr.weight_end, precision: 3) %> kg</td>
      <td><%= link_to 'Editar', edit_admin_price_range_path(pr), class: 'btn btn-outline-warning' %></td>
    </tr>
    <% count += 1 %>
    <% end %>
  </tbody>
</table>

app/views/admin/price_ranges/new.html.erb
<h1 class="text-center">Novo Intervalo de Medida</h1>
<%= render partial: 'form' %>